import { JestConfigWithTsJest } from "ts-jest";
import { resolve } from "path";
import dotenv from "dotenv";
import sharedConfig from "./sharedConfig";

const config: JestConfigWithTsJest = {
  ...sharedConfig,
  testMatch: ["**/*.int.test.ts"],
  testTimeout: 60000 * 2, // 2 minutes timeout
};

// Load environment variables generated by serverless-export-env plugin
dotenv.config({
  path: resolve(__dirname, "../.env.test"),
});

export default config;
